### ISSUE TITLE
brew pkg fails with undefined method

### ISSUE THREAD

**Issue by exprez135** [timsutton/brew-pkg#12]
Hello! I recently installed brew pkg and am experiencing the below error every time I try to use the package. Any idea what's going on here?

```
Warning: Calling Formula#installed? is deprecated! Use Formula#latest_version_installed? (or Formula#any_version_installed? ) instead.
==> Creating package staging root using Homebrew prefix /usr/local
Error: undefined method `with_deps?' for ["tnef"]:Array
/usr/local/bin/brew-pkg.rb:63:in `pkg'
/usr/local/bin/brew-pkg.rb:162:in `<top (required)>'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/usr/local/Homebrew/Library/Homebrew/utils.rb:81:in `require?'
/usr/local/Homebrew/Library/Homebrew/brew.rb:112:in `<main>'
```

I tried with multiple forms:
`brew pkg ffmpeg`
`brew pkg tnef`
With and without --with-deps and --without-kegs. All of them fail with that same sort of error.

**Comment by MAJ007** [comment]
Same issue. @timsutton Any plans to fix?
