### ISSUE TITLE
/usr/local/Cellar query

### ISSUE THREAD

**Issue by andrewvalentine** [timsutton/brew-pkg#8]
Hello!

As per README.md:

> By default behaviour brew pkg include all package kegs located in /usr/local/Cellar/packagename.

I've built some pkgs with brew pkg that don't seem to function as I'd expect, with errors indicating that the required files at /usr/local/Cellar do not exist. For example, I built a package for the the document converter [Pandoc](http://pandoc.org/index.html) as follows:

```
[me@host] ~ > brew install pandoc
==> Downloading https://homebrew.bintray.com/bottles/pandoc-1.17.2.el_capitan.bottle.tar.gz
Already downloaded: /Users/me/Library/Caches/Homebrew/pandoc-1.17.2.el_capitan.bottle.tar.gz
==> Pouring pandoc-1.17.2.el_capitan.bottle.tar.gz
Error: The `brew link` step did not complete successfully
The formula built, but is not symlinked into /usr/local
Could not symlink etc/bash_completion.d/pandoc
Target /usr/local/etc/bash_completion.d/pandoc
already exists. You may want to remove it:
  rm '/usr/local/etc/bash_completion.d/pandoc'

To force the link and overwrite all conflicting files:
  brew link --overwrite pandoc

To list all files that would be deleted:
  brew link --overwrite --dry-run pandoc

Possible conflicting files are:
/usr/local/etc/bash_completion.d/pandoc
/usr/local/bin/pandoc
/usr/local/share/doc/x86_64-osx-ghc-8.0.1/pandoc-1.17.2/COPYING
/usr/local/share/man/man1/pandoc.1
/usr/local/share/x86_64-osx-ghc-8.0.1/pandoc-1.17.2/COPYRIGHT
/usr/local/share/x86_64-osx-ghc-8.0.1/pandoc-1.17.2/README
/usr/local/share/x86_64-osx-ghc-8.0.1/pandoc-1.17.2/data/LaTeXMathML.js
/usr/local/share/x86_64-osx-ghc-8.0.1/pandoc-1.17.2/data/MathMLinHTML.js
/usr/local/share/x86_64-osx-ghc-8.0.1/pandoc-1.17.2/data/bash_completion.tpl
/usr/local/share/x86_64-osx-ghc-8.0.1/pandoc-1.17.2/data/docx/[Content_Types].xml
/usr/local/share/x86_64-osx-ghc-8.0.1/pandoc-1.17.2/data/docx/_rels/.rels
/usr/local/share/x86_64-osx-ghc-8.0.1/pandoc-1.17.2/data/docx/docProps/app.xml
/usr/local/share/x86_64-osx-ghc-8.0.1/pandoc-1.17.2/data/docx/docProps/core.xml
/usr/local/share/x86_64-osx-ghc-8.0.1/pandoc-1.17.2/data/docx/word/_rels/document.xml.rels
/usr/local/share/x86_64-osx-ghc-8.0.1/pandoc-1.17.2/data/docx/word/_rels/footnotes.xml.rels
/usr/local/share/x86_64-osx-ghc-8.0.1/pandoc-1.17.2/data/docx/word/document.xml
/usr/local/share/x86_64-osx-ghc-8.0.1/pandoc-1.17.2/data/docx/word/fontTable.xml
/usr/local/share/x86_64-osx-ghc-8.0.1/pandoc-1.17.2/data/docx/word/footnotes.xml
/usr/local/share/x86_64-osx-ghc-8.0.1/pandoc-1.17.2/data/docx/word/numbering.xml
/usr/local/share/x86_64-osx-ghc-8.0.1/pandoc-1.17.2/data/docx/word/settings.xml
/usr/local/share/x86_64-osx-ghc-8.0.1/pandoc-1.17.2/data/docx/word/styles.xml
/usr/local/share/x86_64-osx-ghc-8.0.1/pandoc-1.17.2/data/docx/word/theme/theme1.xml
/usr/local/share/x86_64-osx-ghc-8.0.1/pandoc-1.17.2/data/docx/word/webSettings.xml
/usr/local/share/x86_64-osx-ghc-8.0.1/pandoc-1.17.2/data/dzslides/template.html
/usr/local/share/x86_64-osx-ghc-8.0.1/pandoc-1.17.2/data/epub.css
/usr/local/share/x86_64-osx-ghc-8.0.1/pandoc-1.17.2/data/odt/Configurations2/accelerator/current.xml
/usr/local/share/x86_64-osx-ghc-8.0.1/pandoc-1.17.2/data/odt/META-INF/manifest.xml
/usr/local/share/x86_64-osx-ghc-8.0.1/pandoc-1.17.2/data/odt/Thumbnails/thumbnail.png
/usr/local/share/x86_64-osx-ghc-8.0.1/pandoc-1.17.2/data/odt/content.xml
/usr/local/share/x86_64-osx-ghc-8.0.1/pandoc-1.17.2/data/odt/manifest.rdf
/usr/local/share/x86_64-osx-ghc-8.0.1/pandoc-1.17.2/data/odt/meta.xml
/usr/local/share/x86_64-osx-ghc-8.0.1/pandoc-1.17.2/data/odt/mimetype
/usr/local/share/x86_64-osx-ghc-8.0.1/pandoc-1.17.2/data/odt/settings.xml
/usr/local/share/x86_64-osx-ghc-8.0.1/pandoc-1.17.2/data/odt/styles.xml
/usr/local/share/x86_64-osx-ghc-8.0.1/pandoc-1.17.2/data/sample.lua
/usr/local/share/x86_64-osx-ghc-8.0.1/pandoc-1.17.2/data/templates/default.asciidoc
/usr/local/share/x86_64-osx-ghc-8.0.1/pandoc-1.17.2/data/templates/default.beamer
/usr/local/share/x86_64-osx-ghc-8.0.1/pandoc-1.17.2/data/templates/default.commonmark
/usr/local/share/x86_64-osx-ghc-8.0.1/pandoc-1.17.2/data/templates/default.context
/usr/local/share/x86_64-osx-ghc-8.0.1/pandoc-1.17.2/data/templates/default.docbook
/usr/local/share/x86_64-osx-ghc-8.0.1/pandoc-1.17.2/data/templates/default.docbook5
/usr/local/share/x86_64-osx-ghc-8.0.1/pandoc-1.17.2/data/templates/default.dokuwiki
/usr/local/share/x86_64-osx-ghc-8.0.1/pandoc-1.17.2/data/templates/default.dzslides
/usr/local/share/x86_64-osx-ghc-8.0.1/pandoc-1.17.2/data/templates/default.epub
/usr/local/share/x86_64-osx-ghc-8.0.1/pandoc-1.17.2/data/templates/default.epub3
/usr/local/share/x86_64-osx-ghc-8.0.1/pandoc-1.17.2/data/templates/default.haddock
/usr/local/share/x86_64-osx-ghc-8.0.1/pandoc-1.17.2/data/templates/default.html
/usr/local/share/x86_64-osx-ghc-8.0.1/pandoc-1.17.2/data/templates/default.html5
/usr/local/share/x86_64-osx-ghc-8.0.1/pandoc-1.17.2/data/templates/default.icml
/usr/local/share/x86_64-osx-ghc-8.0.1/pandoc-1.17.2/data/templates/default.latex
/usr/local/share/x86_64-osx-ghc-8.0.1/pandoc-1.17.2/data/templates/default.man
/usr/local/share/x86_64-osx-ghc-8.0.1/pandoc-1.17.2/data/templates/default.markdown
/usr/local/share/x86_64-osx-ghc-8.0.1/pandoc-1.17.2/data/templates/default.mediawiki
/usr/local/share/x86_64-osx-ghc-8.0.1/pandoc-1.17.2/data/templates/default.opendocument
/usr/local/share/x86_64-osx-ghc-8.0.1/pandoc-1.17.2/data/templates/default.opml
/usr/local/share/x86_64-osx-ghc-8.0.1/pandoc-1.17.2/data/templates/default.org
/usr/local/share/x86_64-osx-ghc-8.0.1/pandoc-1.17.2/data/templates/default.plain
/usr/local/share/x86_64-osx-ghc-8.0.1/pandoc-1.17.2/data/templates/default.revealjs
/usr/local/share/x86_64-osx-ghc-8.0.1/pandoc-1.17.2/data/templates/default.rst
/usr/local/share/x86_64-osx-ghc-8.0.1/pandoc-1.17.2/data/templates/default.rtf
/usr/local/share/x86_64-osx-ghc-8.0.1/pandoc-1.17.2/data/templates/default.s5
/usr/local/share/x86_64-osx-ghc-8.0.1/pandoc-1.17.2/data/templates/default.slideous
/usr/local/share/x86_64-osx-ghc-8.0.1/pandoc-1.17.2/data/templates/default.slidy
/usr/local/share/x86_64-osx-ghc-8.0.1/pandoc-1.17.2/data/templates/default.tei
/usr/local/share/x86_64-osx-ghc-8.0.1/pandoc-1.17.2/data/templates/default.texinfo
/usr/local/share/x86_64-osx-ghc-8.0.1/pandoc-1.17.2/data/templates/default.textile
/usr/local/share/x86_64-osx-ghc-8.0.1/pandoc-1.17.2/data/templates/default.zimwiki
==> Caveats
Bash completion has been installed to:
  /usr/local/etc/bash_completion.d
==> Summary
🍺  /usr/local/Cellar/pandoc/1.17.2: 72 files, 84.8M
[me@host] ~ > brew pkg pandoc
Warning: Calling Formula.factory is deprecated!
Use Formulary.factory instead.
/usr/local/bin/brew-pkg.rb:38:in `pkg'

==> Creating package staging root using Homebrew prefix /usr/local
Warning: Calling Formula.factory is deprecated!
Use Formulary.factory instead.
/usr/local/bin/brew-pkg.rb:65:in `block in pkg'

==> Staging formula pandoc
==> Building package pandoc-1.17.2.pkg
```

I then uninstalled the brew package:

```
[me@host] ~ > brew uninstall pandoc
Uninstalling /usr/local/Cellar/pandoc/1.17.2... (72 files, 84.8M)
[me@host] ~ > brew cleanup
[me@host] ~ > brew prune
```

And installed the built brew pkg:

```
[me@host] ~ > sudo installer -pkg pandoc-1.17.2.pkg -target /
Password:
installer: Package name is pandoc-1.17.2
installer: Upgrading at base path /
installer: The upgrade was successful.
```

I then carried out the test instructions at [Pandoc - Getting Started](http://pandoc.org/getting-started.html):

```
[me@host] ~ > touch test1.md
[me@host] ~ > pandoc test1.md -f markdown -t html -s -o test1.html
pandoc: Could not find data file /usr/local/Cellar/pandoc/1.17.2/share/x86_64-osx-ghc-8.0.1/pandoc-1.17.2/data/templates/default.html
[me@host] ~ >
```

My understanding is that brew pkg includes the package kegs from /usr/local/Cellar for the given formula, but this doesn't seem to be the case in my testing. Have I done something wrong with my initial packaging?

Thanks,

Andrew

**Comment by SkydiveMike** [comment]
I have the same issue. (`watchman` if it matters)
